language: python
python:
  - "2.7"
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
    - libgmp-dev
    - libmpfr-dev
    - ccache
cache: pip
before_install:
  - export PATH=/usr/lib/ccache:$PATH
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - mkdir builds
  - pushd builds
  # Install gmpy2 dependencies
  - mkdir -p $HOME/.local
  - wget ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.2.tar.gz
  - tar xzvf mpc-1.0.2.tar.gz
  - pushd mpc-1.0.2
  - ./configure --prefix=$HOME/.local
  - make
  - make install
  - popd
  - export CPATH=$HOME/.local/include
  - export LIBRARY_PATH=$HOME/.local/lib
  - python -V
  - popd
  - set -o pipefail
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels MDAnalysis
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=2.7 numpy=1.10.2 nose=1.3.7 matplotlib pandas cython=0.23.4 mdanalysis=0.14.0 tempdir
  - source activate test-environment
  - conda install -c https://conda.anaconda.org/ioos testfixtures
  - conda install -c https://conda.anaconda.org/treddy scipy
  - pip install coveralls
  - chmod +x ./
script:
  - nosetests --with-coverage --cover-package voronoi_analysis_library tests.py
after_success:
  - coveralls
