language: python
python:
  - "2.7"
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
    - libgmp-dev
    - libmpfr-dev
    - ccache
cache:
  directories:
    - $HOME/.ccache
before_install:
  - export PATH=/usr/lib/ccache:$PATH
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - mkdir builds
  - pushd builds
  # Install gmpy2 dependencies
  - mkdir -p $HOME/.local
  - wget ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.2.tar.gz
  - tar xzvf mpc-1.0.2.tar.gz
  - pushd mpc-1.0.2
  - ./configure --prefix=$HOME/.local
  - make
  - make install
  - popd
  - export CPATH=$HOME/.local/include
  - export LIBRARY_PATH=$HOME/.local/lib
  - travis_retry pip install --install-option="--no-cython-compile" Cython==0.22
  - travis_retry pip install $NUMPYSPEC
  - travis_retry pip install nose mpmath argparse Pillow
  - travis_retry pip install gmpy2  # speeds up mpmath (scipy.special tests)
  - python -V
  - popd
  - set -o pipefail
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - wget https://github.com/tylerjereddy/scipy.git
install:
  - conda create --yes -q -n pyenv python=2.7 numpy=1.9.2 nose=1.3.7 matplotlib=1.4.2 pandas=0.16.0 cython=0.23.4 openblas=0.2.14
  - source activate pyenv
  - pip install MDAnalysis==0.12.1
  - pip install testfixtures
  - pip install coveralls tempdir
  - chmod +x ./
script:
  - cd scipy
  - python setup.py install
  - cd ..
  - nosetests --with-coverage --cover-package voronoi_analysis_library tests.py
after_success:
  - coveralls
