language: python
python:
  - "2.7"
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
    - libgmp-dev
    - libmpfr-dev
    - ccache
cache: pip
before_install:
  - export PATH=/usr/lib/ccache:$PATH
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - mkdir builds
  - pushd builds
  # Install gmpy2 dependencies
  - mkdir -p $HOME/.local
  - wget ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.2.tar.gz
  - tar xzvf mpc-1.0.2.tar.gz
  - pushd mpc-1.0.2
  - ./configure --prefix=$HOME/.local
  - make
  - make install
  - popd
  - export CPATH=$HOME/.local/include
  - export LIBRARY_PATH=$HOME/.local/lib
  - python -V
  - popd
  - set -o pipefail
  - pip install --quiet numpy==1.9.2 nose==1.3.7 matplotlib==1.4.2 pandas==0.16.0 cython==0.23.4 MDAnalysis==0.12.1 testfixtures coveralls tempdir
  - travis_wait pip install --quiet git+https://github.com/tylerjereddy/scipy.git
  - chmod +x ./
script:
  - nosetests --with-coverage --cover-package voronoi_analysis_library tests.py
after_success:
  - coveralls
